export const eventOptions = [
  { value: "Escape Room", label: "Escape Room" },
  {
    value: "Workshop on Hugging Face Transformers",
    label: "Workshop on Hugging Face Transformers",
  },
  { value: "Data Science Quest", label: "Data Science Quest" },
  { value: "Harmonious Chaos", label: "Harmonious Chaos" },
  { value: "Pixelate", label: "Pixelate" },
  { value: "Code Combat", label: "Code Combat" },
  { value: "ML Hackathon", label: "ML Hackathon" },
  { value: "Investor's edge", label: "Investor's edge" },
  { value: "Best Engineer", label: "Best Engineer" },
  { value: "3D Modeling in Blender", label: "3D Modeling in Blender" },
  { value: "Script Writing Competition", label: "Script Writing Competition" },
  { value: "Battlegrounds India Mobile", label: "Battlegrounds India Mobile" },
  {
    value: "Character Sketching Competition",
    label: "Character Sketching Competition",
  },
  {
    value: "Map Design using Unity Game Engine",
    label: "Map Design using Unity Game Engine",
  },
  { value: "Call of Duty Mobile", label: "Call of Duty Mobile" },
  { value: "Valorant", label: "Valorant" },
  {
    value: "PC Arcade and VR Games Stall",
    label: "PC Arcade and VR Games Stall",
  },
  { value: "Mobile Planetorium Tag", label: "Mobile Planetorium Tag" },
  {
    value: "Harry Potter Quidditch-Inner Spectra Games",
    label: "Harry Potter Quidditch-Inner Spectra Games",
  },
  { value: "Line Follower", label: "Line Follower" },
  { value: "Ingenium 3.0  Hackathon", label: "Ingenium 3.0  Hackathon" },
  { value: "ROS in Edge AI robot", label: "ROS in Edge AI robot" },
  {
    value: "Multi-Sensor Fusion in ADAS",
    label: "Multi-Sensor Fusion in ADAS",
  },
  { value: "Ninja Circuit Challenge", label: "Ninja Circuit Challenge" },
  { value: "Robo - Soccer", label: "Robo - Soccer" },
  {
    value: "PROTO-TRONICS/ EPOCH RUNNERS",
    label: "PROTO-TRONICS/ EPOCH RUNNERS",
  },
  { value: "INNOVATE 1.0 - Ideathon", label: "INNOVATE 1.0 - Ideathon" },
  { value: "Circuit Forge", label: "Circuit Forge" },
  { value: "Laser Tag", label: "Laser Tag" },
  { value: "Prompt with Me", label: "Prompt with Me" },
  {
    value: "Palm LLM, build me a website",
    label: "Palm LLM, build me a website",
  },
  {
    value: "Scene understanding using Computer Vision Techniques",
    label: "Scene understanding using Computer Vision Techniques",
  },
  { value: "Crack the Bug", label: "Crack the Bug" },
  {
    value: "EVIL unDEAD : the broken seal",
    label: "EVIL unDEAD : the broken seal",
  },
  {
    value: "L.A.W : Legal Appellant War",
    label: "L.A.W : Legal Appellant War",
  },
  { value: "S.O.S : Shoot On Sight ", label: "S.O.S : Shoot On Sight " },
  {
    value: "Riddle Realm: Win as you solve",
    label: "Riddle Realm: Win as you solve",
  },
  { value: "Gen AI Workshop", label: "Gen AI Workshop" },
  { value: "ByteBlitz Showtime", label: "ByteBlitz Showtime" },
  { value: "Madness in Metaverse", label: "Madness in Metaverse" },
  { value: "WPM Wars", label: "WPM Wars" },
  { value: "Code Swap", label: "Code Swap" },
  { value: "Code in Unknown Language", label: "Code in Unknown Language" },
  { value: "Code Inverse", label: "Code Inverse" },
  { value: "FanDom Wars", label: "FanDom Wars" },
  { value: "Google Assistant Hack day", label: "Google Assistant Hack day" },
  { value: "ChipBlitz", label: "ChipBlitz" },
  { value: "Knowledge Knockout", label: "Knowledge Knockout" },
  { value: "Tinkerit", label: "Tinkerit" },
  { value: "Lyric-O-Holic", label: "Lyric-O-Holic" },
  { value: "Digital Escape Den", label: "Digital Escape Den " },
  { value: "Quantathon", label: "Quantathon" },
  { value: "Cinesnap", label: "Cinesnap" },
  { value: "BitWizards", label: "BitWizards" },
  { value: "Shutter Showcase", label: "Shutter Showcase" },
  { value: "Technovation", label: "Technovation" },
  { value: "Srujan", label: "Srujan" },
  { value: "Reels Rush Rally", label: "Reels Rush Rally" },
  { value: "Maze Solver", label: "Maze Solver" },
  { value: "Robotics Workshop", label: "Robotics Workshop" },
  { value: "Flyway Fury", label: "Flyway Fury" },
  { value: "Mech Trivia", label: "Mech Trivia" },
  { value: "Robo Grand Prix", label: "Robo Grand Prix" },
  { value: "Flash", label: "Flash" },
  { value: "Web Designing", label: "Web Designing" },
  { value: "Code Blind", label: "Code Blind" },
  { value: "Squid game", label: "Squid game" },
  { value: "Colay 2.0", label: "Colay 2.0" },
];
